"""卡牌中文资产：key→中文名、牌型中文名、效果描述英→中翻译（观测台显示用）。

数据源：balatrobot 文档的 266 张卡（card_desc.py）；名称采用官方简中或通用译名，
个别冷门卡为直译。描述翻译为规则式（词表替换），保证观测台无英文残留。
"""
from __future__ import annotations

import re

from card_desc import CARD_DESC

# 牌型中文名
HAND_ZH = {
    "High Card": "高牌", "Pair": "对子", "Two Pair": "两对",
    "Three of a Kind": "三条", "Straight": "顺子", "Flush": "同花",
    "Full House": "葫芦", "Four of a Kind": "四条", "Straight Flush": "同花顺",
    "Five of a Kind": "五条", "Flush House": "花葫芦", "Flush Five": "同花五",
}

NAME_ZH: dict[str, str] = {
    # ---- 小丑（150）----
    "j_joker": "小丑", "j_greedy_joker": "贪婪小丑", "j_lusty_joker": "色欲小丑",
    "j_wrathful_joker": "愤怒小丑", "j_gluttenous_joker": "暴食小丑",
    "j_jolly": "欢乐小丑", "j_zany": "古怪小丑", "j_mad": "疯狂小丑",
    "j_crazy": "狂野小丑", "j_droll": "诙谐小丑", "j_sly": "狡黠小丑",
    "j_wily": "机敏小丑", "j_clever": "伶俐小丑", "j_devious": "阴险小丑",
    "j_crafty": "灵巧小丑", "j_half": "半张小丑", "j_stencil": "蜡纸小丑",
    "j_four_fingers": "四指小丑", "j_mime": "哑剧小丑", "j_credit_card": "信用卡",
    "j_ceremonial": "祭礼小丑", "j_smeared": "涂抹小丑", "j_8_ball": "8号球",
    "j_abstract": "抽象小丑", "j_burnt": "烧焦小丑", "j_delayed_grat": "延迟满足",
    "j_faceless": "无面小丑", "j_gift": "礼物", "j_turtle_bean": "龟豆",
    "j_egg": "蛋", "j_ice_cream": "冰淇淋", "j_bull": "公牛", "j_marble": "大理石",
    "j_dna": "DNA", "j_certificate": "证书", "j_trading": "交易卡",
    "j_flower_pot": "花盆", "j_blue_joker": "蓝色小丑", "j_hallucination": "幻觉",
    "j_fortune_teller": "算命先生", "j_smiley": "微笑小丑", "j_golden": "金票",
    "j_business": "商务卡", "j_rocket": "火箭", "j_obelisk": "方尖碑",
    "j_cavendish": "卡文迪什", "j_gros_michel": "大米歇尔", "j_triboulet": "特里布莱",
    "j_yorick": "约里克", "j_chicot": "奇科", "j_perkeo": "佩尔可",
    "j_caino": "卡伊诺", "j_raised_fist": "举拳", "j_misprint": "印刷错误",
    "j_burglar": "窃贼", "j_drunkard": "醉汉", "j_troubadour": "游吟诗人",
    "j_merry_andy": "快乐安迪", "j_loyalty_card": "会员卡", "j_bootstraps": "靴带",
    "j_popcorn": "爆米花", "j_ramen": "拉面", "j_selzer": "苏打水",
    "j_throwback": "旧爱", "j_to_the_moon": "冲向月亮", "j_vampire": "吸血鬼",
    "j_ride_the_bus": "坐公交", "j_green_joker": "绿色小丑", "j_supernova": "超新星",
    "j_runner": "奔跑者", "j_flash": "闪光", "j_bloodstone": "血石",
    "j_arrowhead": "箭头", "j_onyx_agate": "缟玛瑙", "j_glass": "玻璃小丑",
    "j_constellation": "星座", "j_hack": "劈砍", "j_sock_and_buskin": "袜子与木屐",
    "j_swashbuckler": "海盗", "j_trousers": "长裤", "j_square": "正方形",
    "j_seance": "通灵会", "j_superposition": "叠加态", "j_oops": "哎呀",
    "j_idol": "偶像", "j_seeing_double": "看见双数", "j_matador": "斗牛士",
    "j_hit_the_road": "上路", "j_dusk": "黄昏", "j_shoot_the_moon": "射月",
    "j_drivers_license": "驾照", "j_banner": "横幅", "j_mystic_summit": "神秘峰",
    "j_acrobat": "杂技演员", "j_vagabond": "流浪者", "j_reserved_parking": "预留车位",
    "j_mail": "邮件", "j_todo_list": "待办清单", "j_space": "太空小丑",
    "j_cartomancer": "制图师", "j_astronomer": "天文学家", "j_cloud_9": "九霄云上",
    "j_satellite": "卫星", "j_luchador": "摔跤手", "j_chaos": "混沌",
    "j_mr_bones": "骨头先生", "j_invisible": "隐形人", "j_brainstorm": "头脑风暴",
    "j_hanging_chad": "悬挂的纸屑", "j_sixth_sense": "第六感",
    "j_rough_gem": "粗宝石", "j_pareidolia": "空想性错视", "j_hiker": "徒步者",
    "j_certificate": "证书", "j_blackboard": "黑板", "j_tribe": "部落",
    "j_order": "秩序", "j_family": "家族", "j_trio": "三重奏", "j_duo": "二重奏",
    "j_baseball": "棒球卡", "j_campfire": "营火", "j_ticket": "票根",
    "j_stuntman": "特技演员", "j_odd_todd": "奇数陶德", "j_even_steven": "偶数史蒂文",
    "j_scholar": "学者", "j_walkie_talkie": "对讲机", "j_shortcut": "捷径",
    "j_midas_mask": "弥达斯面具", "j_lucky_cat": "幸运猫", "j_ancient": "远古小丑",
    "j_steel_joker": "钢铁小丑", "j_stone": "石头小丑", "j_scary_face": "吓人的脸",
    "j_fibonacci": "斐波那契", "j_juggler": "杂耍者", "j_wee": "小不点",
    "j_castle": "城堡", "j_hologram": "全息影像", "j_photograph": "照片",
    "j_red_card": "红牌", "j_madness": "疯癫", "j_erosion": "侵蚀",
    "j_diet_cola": "减肥可乐", "j_riff_raff": "乌合之众", "j_baron": "男爵",
    "j_blueprint": "蓝图", "j_card_sharp": "卡牌老手", "j_ring_master": "马戏班主",
    "j_splash": "水花小丑",
    # ---- 星球（13）----
    "c_mercury": "水星(升对子)", "c_venus": "金星(升三条)", "c_earth": "地球(升葫芦)",
    "c_mars": "火星(升四条)", "c_jupiter": "木星(升同花)", "c_saturn": "土星(升顺子)",
    "c_uranus": "天王星(升两对)", "c_neptune": "海王星(升同花顺)",
    "c_pluto": "冥王星(升高牌)", "c_planet_x": "行星X(升五条)",
    "c_ceres": "谷神星(升花葫芦)", "c_eris": "阖神星(升同花五)",
    "c_black_hole": "黑洞(升全部)",
    # ---- 塔罗（22）----
    "c_fool": "愚者", "c_magician": "魔术师", "c_high_priestess": "女祭司",
    "c_empress": "皇后", "c_heirophant": "教皇", "c_lovers": "恋人",
    "c_chariot": "战车", "c_justice": "正义", "c_hermit": "隐士",
    "c_wheel_of_fortune": "命运之轮", "c_strength": "力量",
    "c_hanged_man": "倒吊人", "c_death": "死神", "c_temperance": "节制",
    "c_devil": "恶魔", "c_tower": "高塔", "c_star": "星星", "c_moon": "月亮",
    "c_sun": "太阳", "c_judgement": "审判", "c_world": "世界", "c_emperor": "皇帝",
    # ---- 幻灵（17）----
    "c_familiar": "魔宠", "c_grim": "冷酷魔灵", "c_incantation": "咒语",
    "c_soul": "灵魂", "c_ectoplasm": "灵质", "c_immolate": "焚祭",
    "c_ankh": "安卡", "c_deja_vu": "似曾相识", "c_hex": "巫咒",
    "c_trance": "催眠", "c_medium": "通灵", "c_cryptid": "神秘生物",
    "c_sigil": "印记", "c_ouija": "通灵板", "c_talisman": "护符",
    "c_aura": "光环", "c_wraith": "幽灵",
    # ---- 兑换券（32）----
    "v_antimatter": "反物质", "v_blank": "空白", "v_clearance_sale": "清仓大甩卖",
    "v_crystal_ball": "水晶球", "v_directors_cut": "导演剪辑",
    "v_glow_up": "蜕变", "v_grabber": "抢夺者", "v_hieroglyph": "象形文字",
    "v_hone": "磨刀石", "v_illusion": "幻象", "v_liquidation": "清算",
    "v_magic_trick": "魔术戏法", "v_money_tree": "摇钱树",
    "v_nacho_tong": "纳乔夹", "v_observatory": "天文台", "v_omen_globe": "凶兆球",
    "v_overstock_norm": "大库存", "v_overstock_plus": "大库存·极",
    "v_paint_brush": "油漆刷", "v_palette": "调色板", "v_petroglyph": "岩画",
    "v_planet_merchant": "星球商贩", "v_planet_tycoon": "星球大亨",
    "v_recyclomancy": "回收术", "v_reroll_glut": "重掷狂潮",
    "v_reroll_surplus": "重掷盈余", "v_retcon": "改写", "v_seed_money": "种子资金",
    "v_tarot_merchant": "塔罗商贩", "v_tarot_tycoon": "塔罗大亨",
    "v_telescope": "望远镜", "v_wasteful": "浪费",
}

# 卡包：p_<类>_<规格>_<编号> → 中文名
_PACK_KIND = {"arcana": "奥术包", "buffoon": "小丑包", "celestial": "天体包",
              "spectral": "幻灵包", "standard": "标准包"}
_PACK_SIZE = {"normal": "普通", "jumbo": "加大", "mega": "巨型"}


def pack_zh(key: str) -> str:
    m = re.match(r"p_(\w+?)_(normal|jumbo|mega)_\d+$", key)
    if m:
        return f"{_PACK_SIZE[m.group(2)]}{_PACK_KIND.get(m.group(1), m.group(1))}"
    return NAME_ZH.get(key, key)


def card_zh(key: str) -> str:
    """卡牌 key → 中文名（观测台显示统一入口）。"""
    if key in NAME_ZH:
        return NAME_ZH[key]
    if key.startswith("p_"):
        return pack_zh(key)
    return key


# ---------------------------------------------------------------------------
# 效果描述英→中（词表按长度降序替换，覆盖 balatrobot 文档常见句式）
# ---------------------------------------------------------------------------
_DESC_PHRASES: list[tuple[str, str]] = [
    ("Retrigger all cards held in hand abilities", "重触发所有在手牌的效果"),
    ("Adds double the rank of lowest ranked held card to Mult",
     "将在手最低点数×2加到倍率"),
    ("Retrigger first played card used in scoring 2 additional times",
     "首张计分牌额外重触发2次"),
    ("Retrigger all played cards in final hand of the round",
     "本回合最后一手牌全部重触发"),
    ("Each played card with specific suit gives X1.5 Mult",
     "每张指定花色的计分牌×1.5倍率(每轮变换)"),
    ("Each played card of specific rank and suit gives X2 Mult",
     "每张指定点数+花色的计分牌×2倍率(每轮变换)"),
    ("Gives X0.2 Mult for each Steel Card in your full deck",
     "整个牌组每张钢牌×0.2倍率"),
    ("Gives +25 Chips for each Stone Card in your full deck",
     "整个牌组每张石牌+25筹码"),
    ("Gives X3 Mult if you have at least 16 Enhanced cards in your full deck",
     "牌组中≥16张强化牌时×3倍率"),
    ("X3 Mult if you have at least 16 Enhanced cards in your full deck",
     "牌组中≥16张强化牌时×3倍率"),
    ("Uncommon Jokers each give X1.5 Mult", "每张非普通小丑×1.5倍率"),
    ("X2 Mult if played hand has a scoring Club and a card of any other suit",
     "计分含梅花且另有其他花色时×2倍率"),
    ("Adds the sell value of all other owned Jokers to Mult",
     "其他小丑的卖价总和加到倍率"),
    ("Creates a copy of a random Joker", "复制一个随机小丑"),
    ("destroy all other Jokers", "摧毁其余全部小丑"),
    ("Adds a Polychrome edition to a random Joker", "给随机小丑上多彩版本"),
    ("Adds X4 Mult if played hand contains", "打出的牌型包含以下牌时×4倍率"),
    ("Gains +Chips if played hand has exactly", "打出的牌张数恰为指定值时累积筹码"),
    ("Played face cards give +30 Chips when scored", "人脸计分牌+30筹码"),
    ("Gains +Mult when any Booster Pack is skipped", "每跳过一个卡包累积倍率"),
    ("+1 Mult per Tarot card used this run", "本局每用一张塔罗+1倍率"),
    ("If played hand has exactly", "打出的牌张数恰为"),
    ("each played 2 is scored", "每张点数2计分"),
    ("Increases level of played poker hand", "升级打出的牌型"),
    ("X1.5 Mult for each", "每有1个×1.5倍率"),
    ("gives X Mult", "提供×倍率"),
    ("gives +Mult", "提供+倍率"),
    ("give +Mult", "+倍率"),
    ("give +Chips", "+筹码"),
    ("gives +Chips", "提供+筹码"),
    ("held in hand", "在手"),
    ("in your full deck", "整个牌组中"),
    ("this run", "本局"),
    ("this round", "本回合"),
    ("Played cards", "打出的牌"),
    ("played hand", "打出的牌型"),
    ("played card", "打出的牌"),
    ("when scored", "计分时"),
    ("each discard", "每次弃牌"),
    ("each remaining", "每个剩余"),
    ("remaining discards", "剩余弃牌次数"),
    ("Enhanced card", "强化牌"),
    ("Stone Card", "石牌"),
    ("Steel Card", "钢牌"),
    ("face card", "人头牌"),
    ("Joker", "小丑"),
    ("Mult", "倍率"),
    ("Chips", "筹码"),
    ("money", "金币"),
    ("dollar", "美元"),
    ("blind", "盲注"),
    ("retrigger", "重触发"),
    ("Retrigger", "重触发"),
    ("destroy", "摧毁"),
    ("destroyed", "摧毁"),
    ("create", "生成"),
    ("Creates", "生成"),
    ("copies", "复制"),
    ("Copies", "复制"),
    ("Gains", "累积"),
    ("gains", "累积"),
    ("level up", "升级"),
    ("Level up", "升级"),
    ("probability", "概率"),
    ("scoring", "计分"),
    ("scored", "计分"),
    ("selected", "选中"),
    ("enhancement", "强化"),
    ("becomes", "变为"),
    ("become", "变为"),
    ("converts", "转化为"),
    ("Converts", "转化为"),
    ("random", "随机"),
    ("Random", "随机"),
    ("suits", "花色"),
    ("suit", "花色"),
    ("rank", "点数"),
    ("cards", "牌"),
    ("card", "牌"),
    ("hand", "手牌"),
    ("draw", "抽牌"),
    ("discard", "弃牌"),
    ("interest", "利息"),
    ("sell", "卖出"),
    ("sold", "卖出"),
    ("buy", "购买"),
    ("cost", "花费"),
    ("slot", "槽位"),
    ("empty", "空"),
    ("currently", "当前"),
    ("each", "每"),
    ("per", "每"),
    ("and", "和"),
    ("with", "带有"),
    ("for", "换取"),
    ("if", "若"),
    ("If", "若"),
    ("all", "全部"),
    ("other", "其他"),
    ("owned", "持有"),
    ("Adds", "添加"),
    ("adds", "添加"),
    ("Increase", "提升"),
    ("upgrade", "升级"),
    ("upgrades", "升级"),
    ("extra", "额外"),
    ("additional", "追加"),
    ("opposite", "相反"),
    ("final", "最后"),
    ("first", "首张"),
    ("round", "回合"),
    ("Blind", "盲注"),
    ("skip", "跳过"),
    ("skipped", "跳过"),
    ("Booster Pack", "卡包"),
    ("at end of round", "回合结束时"),
    ("at the end of round", "回合结束时"),
    ("enhance", "强化"),
    ("Enhance", "强化"),
    ("Lucky card", "幸运牌"),
    ("Glass card", "玻璃牌"),
    ("Steel card", "钢牌"),
    ("Gold card", "金牌"),
    ("Bonus card", "奖励牌"),
    ("Mult card", "倍率牌"),
    ("Wild card", "百搭牌"),
    ("Stone card", "石牌"),
    ("Red Seal", "红印记"),
    ("Blue Seal", "蓝印记"),
    ("Purple Seal", "紫印记"),
    ("Gold Seal", "金印记"),
    ("Negative", "负片"),
    ("Polychrome", "多彩"),
    ("Holographic", "镭射"),
    ("Foil", "闪箔"),
    ("Eternal", "永恒"),
    ("Perishable", "易逝"),
    ("Rental", "租金"),
    ("Edition", "版本"),
    ("Seal", "印记"),
]


_DESC_PHRASES2: list[tuple[str, str]] = [
    # 第二遍：句式骨架与词表遗漏（含牌型/花色词）
    ("Create a copy of a", "复制一张"), ("Create 2 copies of", "复制两张"),
    ("Create a copy of", "复制一张"), ("Create up to", "生成至多"),
    ("Upgrade every poker hand by 1 level", "全部牌型升1级"),
    ("Raises level of", "升级牌型"), ("Raise level of", "升级牌型"),
    ("value by", "数值提高"), ("Must have room", "需有空位"),
    ("Add a", "添加"), ("Add an", "添加"), ("Add", "添加"),
    ("effect to 1 selected card", "效果到1张选中牌"),
    ("to 1 selected card", "到1张选中牌"),
    ("Converts 1 selected card into", "把1张选中牌变为"),
    ("Enhances 1 selected card into a", "把1张选中牌强化为"),
    ("Enhances 1 selected card into", "把1张选中牌强化为"),
    ("into the right card", "为右侧牌"), ("the left card", "左侧牌"),
    ("convert", "转化"), ("Convert", "转化"),
    ("Select 2 cards", "选择2张牌"), ("Select", "选择"),
    ("Gold Card", "金牌"), ("gold card", "金牌"),
    ("Heart card", "红桃牌"), ("Diamond card", "方块牌"),
    ("Spade card", "黑桃牌"), ("Club card", "梅花牌"),
    ("Heart", "红桃"), ("Diamond", "方块"), ("Spade", "黑桃"), ("Club", "梅花"),
    ("Flush House", "花葫芦"), ("Straight Flush", "同花顺"),
    ("Four of a Kind", "四条"), ("Three of a Kind", "三条"),
    ("Five of a Kind", "五条"), ("Two Pair", "两对"), ("Flush Five", "同花五"),
    ("High Card", "高牌"), ("Straight", "顺子"), ("Flush", "同花"), ("Pair", "对子"),
    ("poker hand", "牌型"), ("hand size", "手牌上限"), ("size", "上限"),
    ("Tarot", "塔罗"), ("Planet", "星球"), ("Spectral", "幻灵"),
    ("Booster Pack", "卡包"), ("Booster", "卡包"),
    ("1 in 2 chance", "1/2概率"), ("1 in 3 chance", "1/3概率"),
    ("1 in 4 chance", "1/4概率"), ("1 in 5 chance", "1/5概率"),
    ("chance", "概率"), ("Earn", "获得"), ("earn", "获得"),
    ("when sold", "卖出时"), ("sell value", "卖价"),
    ("in your hand", "在手"), ("in hand", "在手"),
    ("this blind", "本盲注"), ("X Mult", "×倍率"), ("X Chips", "×筹码"),
    ("up to", "至多"), ("copies", "份"), ("copy", "份"),
    ("currently", "当前"), ("Currently", "当前"),
    ("play", "打出"), ("Play", "打出"), ("played", "打出"),
    ("first played", "首个打出"), ("held", "持有"),
    ("lowest ranked", "点数最低"), ("highest ranked", "点数最高"),
    ("rank", "点数"), ("ranks", "点数"),
    ("extras", "额外"), ("extra", "额外"),
    ("loses", "失去"), ("lose", "失去"), ("Lost", "失去"),
    ("max", "上限"), ("min", "下限"),
    ("dollars", "美元"), ("dollar", "美元"),
    ("X1", "×1"), ("X2", "×2"), ("X3", "×3"), ("X4", "×4"),
    ("Mult", "倍率"), ("Chips", "筹码"),
]

# 残余功能词（冠词/介词/连词等）直接剔除
_STOP_RE = re.compile(
    r"\b(of|the|a|an|to|is|are|it|its|for|from|on|at|by|or|and|into|up|if|than|"
    r"more|less|most|every|any|all|other|this|that|these|those|card|cards)\b", re.I)


def desc_zh(desc: str) -> str:
    """规则式英→中效果描述翻译（两遍词表 + 残余功能词清除）。"""
    if not desc:
        return ""
    out = desc
    for tbl in (_DESC_PHRASES, _DESC_PHRASES2):
        for en, zh in tbl:
            out = out.replace(en, zh)
    out = _STOP_RE.sub("", out)
    out = re.sub(r"\s{2,}", " ", out).strip()
    return out


# ---------------------------------------------------------------------------
# 手翻效果描述（对着 balatrobot 原文逐卡翻译；未收录的走规则式兜底）
# ---------------------------------------------------------------------------
DESC_HAND_ZH: dict[str, str] = {
    # ---- 塔罗/星球/幻灵 ----
    "c_ankh": "复制一个随机小丑，摧毁其余全部小丑",
    "c_aura": "给1张选中牌添加闪箔/镭射/多彩版本",
    "c_black_hole": "全部牌型升1级",
    "c_ceres": "花葫芦 +4倍率 +40筹码",
    "c_chariot": "把1张选中牌变为钢牌",
    "c_cryptid": "复制1张选中牌×2",
    "c_death": "选2张牌，左侧牌变为右侧牌",
    "c_deja_vu": "给1张选中牌加红印记",
    "c_devil": "把1张选中牌变为金牌",
    "c_earth": "葫芦 +2倍率 +25筹码",
    "c_ectoplasm": "给随机小丑上负片，-1手牌上限",
    "c_emperor": "生成至多2张随机塔罗(需空位)",
    "c_empress": "把2张选中牌变为倍率牌",
    "c_eris": "同花五 +3倍率 +50筹码",
    "c_familiar": "毁手中1张随机牌，加3张随机强化人头牌",
    "c_fool": "生成本局最后用过的塔罗/星球(愚者除外)",
    "c_grim": "毁手中1张随机牌，加2张随机强化A",
    "c_hanged_man": "摧毁至多2张选中的牌",
    "c_heirophant": "把2张选中牌变为奖励牌",
    "c_hermit": "金币翻倍(上限$20)",
    "c_hex": "给随机小丑上多彩，摧毁其余全部小丑",
    "c_high_priestess": "生成至多2张随机星球(需空位)",
    "c_immolate": "毁手中5张随机牌，获得$20",
    "c_incantation": "毁手中1张随机牌，加4张随机强化数字牌",
    "c_judgement": "生成一个随机小丑(需空位)",
    "c_jupiter": "同花 +2倍率 +15筹码",
    "c_justice": "把1张选中牌变为玻璃牌",
    "c_lovers": "把1张选中牌变为百搭牌",
    "c_magician": "把2张选中牌变为幸运牌",
    "c_mars": "四条 +3倍率 +30筹码",
    "c_medium": "给1张选中牌加紫印记",
    "c_mercury": "对子 +1倍率 +15筹码",
    "c_moon": "把至多3张选中牌变为梅花",
    "c_neptune": "同花顺 +4倍率 +40筹码",
    "c_ouija": "手中全部牌变为同一随机点数(-1手牌上限)",
    "c_planet_x": "五条 +3倍率 +35筹码",
    "c_pluto": "高牌 +1倍率 +10筹码",
    "c_saturn": "顺子 +3倍率 +30筹码",
    "c_sigil": "手中全部牌变为同一随机花色",
    "c_soul": "生成一个传奇小丑(需空位)",
    "c_star": "把至多3张选中牌变为方块",
    "c_strength": "至多2张选中牌点数+1",
    "c_sun": "把至多3张选中牌变为红桃",
    "c_talisman": "给1张选中牌加金印记",
    "c_temperance": "获得当前全部小丑卖价之和(上限$50)",
    "c_tower": "把1张选中牌变为石牌",
    "c_trance": "给1张选中牌加蓝印记",
    "c_uranus": "两对 +1倍率 +20筹码",
    "c_venus": "三条 +2倍率 +20筹码",
    "c_wheel_of_fortune": "1/4概率给随机小丑上闪箔/镭射/多彩",
    "c_world": "把至多3张选中牌变为黑桃",
    "c_wraith": "生成随机稀有小丑，金币清零",
    # ---- 小丑 ----
    "j_8_ball": "每张打出的8计分时 1/4概率生成塔罗",
    "j_abstract": "每个小丑+3倍率",
    "j_acrobat": "本回合最后一手×3倍率",
    "j_ancient": "每张指定花色计分牌×1.5倍率(每轮换花色)",
    "j_arrowhead": "黑桃计分牌+50筹码",
    "j_astronomer": "商店里星球牌和天体包免费",
    "j_banner": "每个剩余弃牌次数+30筹码",
    "j_baron": "每张在手的K ×1.5倍率",
    "j_baseball": "每张非普通小丑×1.5倍率",
    "j_blackboard": "在手牌全为黑桃/梅花时×3倍率",
    "j_bloodstone": "红桃计分牌 1/2概率×1.5倍率",
    "j_blue_joker": "牌组每张剩余牌+2筹码",
    "j_blueprint": "复制右侧小丑的能力",
    "j_bootstraps": "每$5金币+2倍率",
    "j_brainstorm": "复制最左侧小丑的能力",
    "j_bull": "每$1金币+2筹码",
    "j_burglar": "选盲时+3手牌数，弃牌次数清零",
    "j_burnt": "每回合首个被弃牌的牌型升1级",
    "j_business": "人头牌计分时 1/2概率+$2",
    "j_caino": "每有人头牌被摧毁 ×1倍率累积",
    "j_campfire": "每卖一张牌×0.25倍率，击败首领盲后重置",
    "j_card_sharp": "本回合已打过的牌型再打×3倍率",
    "j_cartomancer": "选盲时生成一张塔罗",
    "j_castle": "每弃一张指定花色牌+3筹码(每轮换)",
    "j_cavendish": "×3倍率，回合结束 1/1000 概率自毁",
    "j_ceremonial": "选盲时摧毁右侧小丑，其卖价×2加到倍率",
    "j_certificate": "回合开始加1张随机印记牌到手",
    "j_chaos": "每商店1次免费重掷",
    "j_chicot": "禁用所有首领盲效果",
    "j_clever": "两对+80筹码",
    "j_cloud_9": "回合结束时牌组每张9 +$1",
    "j_constellation": "每用一张星球 ×0.1倍率累积",
    "j_crafty": "同花+80筹码",
    "j_crazy": "顺子+12倍率",
    "j_credit_card": "允许透支至-$20",
    "j_delayed_grat": "回合结束时未用弃牌则每次+$2",
    "j_devious": "顺子+100筹码",
    "j_diet_cola": "卖出时生成免费双倍标签",
    "j_dna": "首手只出1张牌时，永久复制进牌组",
    "j_drivers_license": "牌组≥16张强化牌时×3倍率",
    "j_droll": "同花+10倍率",
    "j_drunkard": "每回合+1弃牌次数",
    "j_duo": "对子×2倍率",
    "j_dusk": "最后一手打出的牌全部重触发",
    "j_egg": "回合结束卖价+$3",
    "j_erosion": "牌组每少一张起始牌+4倍率",
    "j_even_steven": "偶数点计分牌+4倍率",
    "j_faceless": "一次弃≥3张人头牌时+$5",
    "j_family": "四条×4倍率",
    "j_fibonacci": "A/2/3/5/8计分牌各+8倍率",
    "j_flash": "商店每次重掷+2倍率累积",
    "j_flower_pot": "计分含全部4花色时×3倍率",
    "j_fortune_teller": "本局每用一张塔罗+1倍率",
    "j_four_fingers": "同花/顺子4张即可成立",
    "j_gift": "回合结束所有小丑和消耗牌卖价+$1",
    "j_glass": "每有玻璃牌被摧毁×0.75倍率累积",
    "j_gluttenous_joker": "梅花计分牌+3倍率",
    "j_golden": "回合结束+$4",
    "j_greedy_joker": "方块计分牌+3倍率",
    "j_green_joker": "每打一手+1倍率，每弃一次-1倍率",
    "j_gros_michel": "+15倍率，回合结束 1/6 概率自毁",
    "j_hack": "重触发每张打出的2/3/4/5",
    "j_half": "打出≤3张牌+20倍率",
    "j_hallucination": "每开一包 1/2 概率生成塔罗",
    "j_hanging_chad": "首张计分牌额外重触发2次",
    "j_hiker": "打出的牌永久+5筹码",
    "j_hit_the_road": "本回合每弃一张J ×0.5倍率",
    "j_hologram": "每加一张牌进牌组×0.25倍率",
    "j_ice_cream": "+100筹码，每打一手-5筹码",
    "j_idol": "指定点数+花色的计分牌×2倍率(每轮换)",
    "j_invisible": "2回合后卖出可复制随机小丑",
    "j_joker": "+4倍率",
    "j_jolly": "对子+8倍率",
    "j_juggler": "+1手牌上限",
    "j_loyalty_card": "每打6手×4倍率一次",
    "j_luchador": "卖出时禁用当前首领盲效果",
    "j_lucky_cat": "幸运牌每次触发×0.25倍率累积",
    "j_lusty_joker": "红桃计分牌+3倍率",
    "j_mad": "两对+10倍率",
    "j_madness": "选小/大盲时×0.5倍率累积，毁一随机小丑",
    "j_mail": "每弃指定点数牌+$5(每轮换)",
    "j_marble": "选盲时牌组加一张石牌",
    "j_matador": "打出触发首领盲效果时+$8",
    "j_merry_andy": "+3弃牌次数，-1手牌上限",
    "j_midas_mask": "打出的人头牌计分时变金牌",
    "j_mime": "重触发所有在手牌的效果",
    "j_misprint": "+0~23随机倍率",
    "j_mr_bones": "得分≥需求25%时免死，自毁",
    "j_mystic_summit": "弃牌次数为0时+15倍率",
    "j_obelisk": "连续不打最常用牌型，每手×0.2倍率",
    "j_odd_todd": "奇数点计分牌+31筹码",
    "j_onyx_agate": "梅花计分牌+7倍率",
    "j_oops": "全部概率翻倍",
    "j_order": "顺子×3倍率",
    "j_pareidolia": "所有牌视为人头牌",
    "j_perkeo": "商店结束时生成1张负片随机消耗牌",
    "j_photograph": "首张人头计分牌×2倍率",
    "j_popcorn": "+20倍率，每回合-4倍率",
    "j_raised_fist": "在手最低点数牌点数×2加到倍率",
    "j_ramen": "×2倍率，每弃一牌-0.01倍率",
    "j_red_card": "每跳过一个卡包+3倍率累积",
    "j_reserved_parking": "每张在手人头牌 1/2 概率+$1",
    "j_ride_the_bus": "连续打无人头计分牌的手+1倍率",
    "j_riff_raff": "选盲时生成2个普通小丑",
    "j_ring_master": "小丑/塔罗/星球/幻灵可重复出现",
    "j_rocket": "回合结束+$1，击败首领盲后+$2",
    "j_rough_gem": "方块计分牌+$1",
    "j_runner": "打出顺子+15筹码累积",
    "j_satellite": "本局每种用过的星球回合结束+$1",
    "j_scary_face": "人头计分牌+30筹码",
    "j_scholar": "A计分牌+20筹码+4倍率",
    "j_seance": "打出同花顺生成随机幻灵",
    "j_seeing_double": "计分有梅花且有其他花色×2倍率",
    "j_selzer": "之后10手打出的牌全部重触发",
    "j_shoot_the_moon": "每张在手Q +13倍率",
    "j_shortcut": "顺子允许1个点数间隔",
    "j_sixth_sense": "首手单出6时毁掉并生成幻灵",
    "j_sly": "对子+50筹码",
    "j_smeared": "红桃/方块同花色，黑桃/梅花同花色",
    "j_smiley": "人头计分牌+5倍率",
    "j_sock_and_buskin": "重触发所有打出的人头牌",
    "j_space": "1/4概率升级打出的牌型",
    "j_splash": "打出的牌全部计分",
    "j_square": "打出4张牌+4筹码累积",
    "j_steel_joker": "牌组每张钢牌×0.2倍率",
    "j_stencil": "每个空小丑槽×1倍率",
    "j_stone": "牌组每张石牌+25筹码",
    "j_stuntman": "+250筹码，-2手牌上限",
    "j_supernova": "牌型本局已打次数加到倍率",
    "j_superposition": "打出A+顺子生成塔罗",
    "j_swashbuckler": "其他小丑卖价之和加到倍率",
    "j_throwback": "本局每跳一盲×0.25倍率",
    "j_ticket": "金牌计分时+$4",
    "j_to_the_moon": "每$5额外+$1利息",
    "j_todo_list": "打出指定牌型+$4(每轮换)",
    "j_trading": "首次弃牌只弃1张时毁掉+$3",
    "j_tribe": "同花×2倍率",
    "j_triboulet": "K和Q计分牌各×2倍率",
    "j_trio": "三条×3倍率",
    "j_troubadour": "+2手牌上限，-1手牌数",
    "j_trousers": "两对+2倍率累积",
    "j_turtle_bean": "+5手牌上限，每回合-1",
    "j_vagabond": "金币≤$4时打出一手生成塔罗",
    "j_vampire": "每张强化计分牌×0.1倍率并剥夺强化",
    "j_walkie_talkie": "10和4计分牌各+10筹码+4倍率",
    "j_wee": "每张点数2计分+8筹码累积",
    "j_wily": "三条+100筹码",
    "j_wrathful_joker": "黑桃计分牌+3倍率",
    "j_yorick": "每弃23张牌×1倍率",
    "j_zany": "三条+12倍率",
    # ---- 兑换券 ----
    "v_antimatter": "+1小丑槽",
    "v_blank": "什么都不做?",
    "v_clearance_sale": "商店全部卡和包75折",
    "v_crystal_ball": "+1消耗牌槽",
    "v_directors_cut": "每轮1次$10重掷首领盲",
    "v_glow_up": "闪箔/镭射/多彩出现率×4",
    "v_grabber": "永久+1手牌数",
    "v_hieroglyph": "-1底注轮，每回合-1手牌数",
    "v_hone": "闪箔/镭射/多彩出现率×2",
    "v_illusion": "商店的牌可能带强化/版本/印记",
    "v_liquidation": "商店全部卡和包5折",
    "v_magic_trick": "商店里可以买牌组用牌",
    "v_money_tree": "利息上限提至$20",
    "v_nacho_tong": "永久再+1手牌数",
    "v_observatory": "消耗区的星球对其牌型×1.5倍率",
    "v_omen_globe": "奥术包可能出幻灵牌",
    "v_overstock_norm": "商店+1卡位(共3)",
    "v_overstock_plus": "商店+1卡位(共4)",
    "v_paint_brush": "+1手牌上限",
    "v_palette": "再+1手牌上限",
    "v_petroglyph": "再-1底注轮，每回合-1弃牌",
    "v_planet_merchant": "商店星球出现率×2",
    "v_planet_tycoon": "商店星球出现率×4",
    "v_recyclomancy": "永久再+1弃牌次数",
    "v_reroll_glut": "重掷费再降$2",
    "v_reroll_surplus": "重掷费降$2",
    "v_retcon": "无限次$10重掷首领盲",
    "v_seed_money": "利息上限提至$10",
    "v_tarot_merchant": "商店塔罗出现率×2",
    "v_tarot_tycoon": "商店塔罗出现率×4",
    "v_telescope": "天体包必出最常用牌型的星球",
    "v_wasteful": "永久+1弃牌次数",
}

_PACK_DESC = {"arcana": "开出塔罗牌选1张", "buffoon": "开出小丑选1张",
              "celestial": "开出星球牌即用", "spectral": "开出幻灵牌选1张",
              "standard": "开出牌加进牌组"}


def _pack_desc(key: str) -> str:
    import re as _re
    m = _re.match(r"p_(\w+?)_(normal|jumbo|mega)_\d+$", key)
    if m:
        size = _PACK_SIZE[m.group(2)]
        kind = _PACK_KIND.get(m.group(1), m.group(1))
        d = _PACK_DESC.get(m.group(1), "")
        return d
    return ""


# 全表：手翻优先 → 卡包模式 → 规则式兜底
DESC_ZH: dict[str, str] = {}
for _k, _v in CARD_DESC.items():
    if _k in DESC_HAND_ZH:
        DESC_ZH[_k] = DESC_HAND_ZH[_k]
    elif _k.startswith("p_"):
        DESC_ZH[_k] = _pack_desc(_k)
    else:
        DESC_ZH[_k] = desc_zh(_v)


def zh_maps_json() -> str:
    """给 dashboard 注入的 JS 常量（名称/中文描述/英文原文/牌型）。"""
    import json
    names = {k: card_zh(k) for k in CARD_DESC}
    return (f"const CARD_ZH={json.dumps(names, ensure_ascii=False)};\n"
            f"const DESC_ZH={json.dumps(DESC_ZH, ensure_ascii=False)};\n"
            f"const CARD_EN={json.dumps(CARD_DESC, ensure_ascii=False)};\n"
            f"const HAND_ZH={json.dumps(HAND_ZH, ensure_ascii=False)};")


# dashboard 注入用（含英文原文表，供前端把 state 文本里的英文描述整段替换）
CARD_EN_ZH_PAYLOAD = zh_maps_json()
